// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import StopWatchController from "./stop_watch_controller"
application.register("stop-watch", StopWatchController)

import TimerController from "./timer_controller"
application.register("timer", TimerController)

import TrackerController from "./tracker_controller"
application.register("tracker", TrackerController)
