// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckboxController from "./checkbox_controller"
application.register("checkbox", CheckboxController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TrackerController from "./tracker_controller"
application.register("tracker", TrackerController)

import StatusInvoicesController from "./status_invoices_controller"
application.register("status-invoices", StatusInvoicesController)

import PaidController from "./paid_controller"
application.register("paid", PaidController)
